# These tasks will be merged into deployment graph. Here you
# can specify new tasks for any roles, even built-in ones.

- id: glance_net_hiera
  type: puppet
  groups: ['primary-controller', 'controller', 'compute']
  requires: ['hiera']
  required_for: ['globals']
  parameters:
    puppet_manifest: hiera_override.pp
    puppet_modules: puppet/modules:/etc/puppet/modules
    timeout: 300

- id: glance_net_ha_endpoint
  type: puppet
  groups: ['primary-controller']
  requires: ['glance-keystone']
  required_for: ['upload_cirros']
  parameters:
    puppet_manifest: ha_endpoint.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300

- id: glance_net_service_configs.pp
  type: puppet
  groups: ['primary-controller', 'controller', 'compute', 'cinder']
  requires: ['glance']
  parameters:
    puppet_manifest: service_configs.pp
    puppet_modules: /etc/puppet/modules
    timeout: 300
 
